# Generated by Django 5.1.1 on 2025-07-12 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        ('swaps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_swaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='skills_offered',
            field=models.ManyToManyField(related_name='offered_in_swaps', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='skills_wanted',
            field=models.ManyToManyField(related_name='wanted_in_swaps', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_swaps', to=settings.AUTH_USER_MODEL),
        ),
    ]
